version: '1.0'
services:
  redis:
    image: redis
    container_name: 'redis'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379


  app:
    build: ./
    container_name: 'java-app'
    ports:
      - 8084:8084


